-- 0) Pick your DB/Schema
CREATE DATABASE IF NOT EXISTS FINOPS;
CREATE SCHEMA IF NOT EXISTS FINOPS.SNOWFLAKE_USAGE;

-- 1) Daily credits & $ from METERING_DAILY_HISTORY
CREATE TABLE IF NOT EXISTS FINOPS.SNOWFLAKE_USAGE.DAILY_METERING (
  USAGE_DATE DATE,
  SERVICE_TYPE STRING,
  CREDITS_USED NUMBER(38,9),
  EST_COST_USD NUMBER(38,9),
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2) Daily warehouse credits from WAREHOUSE_METERING_HISTORY
CREATE TABLE IF NOT EXISTS FINOPS.SNOWFLAKE_USAGE.DAILY_WAREHOUSE_METERING (
  USAGE_DATE DATE,
  WAREHOUSE_NAME STRING,
  CREDITS_USED_COMPUTE NUMBER(38,9),
  CREDITS_USED_CLOUD_SERVICES NUMBER(38,9),
  CREDITS_USED_TOTAL NUMBER(38,9),
  EST_COST_USD NUMBER(38,9),
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3) Query metrics aggregated per day/warehouse/user/db/type/status from QUERY_HISTORY
CREATE TABLE IF NOT EXISTS FINOPS.SNOWFLAKE_USAGE.DAILY_QUERY_METRICS (
  USAGE_DATE DATE,
  WAREHOUSE_NAME STRING,
  DATABASE_NAME STRING,
  SCHEMA_NAME STRING,
  USER_NAME STRING,
  ROLE_NAME STRING,
  QUERY_TYPE STRING,
  EXECUTION_STATUS STRING,
  QUERY_COUNT NUMBER(38,0),
  TOTAL_ELAPSED_MS NUMBER(38,0),
  AVG_ELAPSED_MS NUMBER(38,2),
  TOTAL_BYTES_SCANNED NUMBER(38,0),
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4) Hour-of-week usage heatmap (credits by DOW + hour + warehouse)
CREATE TABLE IF NOT EXISTS FINOPS.SNOWFLAKE_USAGE.HOURLY_WAREHOUSE_CREDITS (
  DOW NUMBER(1,0),          -- 1=Mon..7=Sun
  HOUR_OF_DAY NUMBER(2,0),  -- 0..23
  WAREHOUSE_NAME STRING,
  CREDITS_USED NUMBER(38,9),
  EST_COST_USD NUMBER(38,9),
  USAGE_DATE_FROM DATE,
  USAGE_DATE_TO DATE,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5) Storage daily (optional)
CREATE TABLE IF NOT EXISTS FINOPS.SNOWFLAKE_USAGE.DAILY_STORAGE (
  USAGE_DATE DATE,
  DATABASE_NAME STRING,
  AVERAGE_DATABASE_BYTES NUMBER(38,0),
  AVERAGE_FAILSAFE_BYTES NUMBER(38,0),
  EST_STORAGE_GB NUMBER(38,2),
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
