-- Change these values as needed:
SET CREDIT_PRICE = 3.00;
SET DAYS_BACK = 90;

-- A) DAILY_METERING refresh
DELETE FROM FINOPS.SNOWFLAKE_USAGE.DAILY_METERING
WHERE USAGE_DATE >= DATEADD('day', -$DAYS_BACK, CURRENT_DATE());

INSERT INTO FINOPS.SNOWFLAKE_USAGE.DAILY_METERING (USAGE_DATE, SERVICE_TYPE, CREDITS_USED, EST_COST_USD)
SELECT
  USAGE_DATE::DATE AS USAGE_DATE,
  SERVICE_TYPE,
  SUM(CREDITS_USED) AS CREDITS_USED,
  SUM(CREDITS_USED) * $CREDIT_PRICE AS EST_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE USAGE_DATE::DATE >= DATEADD('day', -$DAYS_BACK, CURRENT_DATE())
GROUP BY 1,2;

-- B) DAILY_WAREHOUSE_METERING refresh (warehouse_metering_history is by start_time)
DELETE FROM FINOPS.SNOWFLAKE_USAGE.DAILY_WAREHOUSE_METERING
WHERE USAGE_DATE >= DATEADD('day', -$DAYS_BACK, CURRENT_DATE());

INSERT INTO FINOPS.SNOWFLAKE_USAGE.DAILY_WAREHOUSE_METERING
(
  USAGE_DATE, WAREHOUSE_NAME,
  CREDITS_USED_COMPUTE, CREDITS_USED_CLOUD_SERVICES, CREDITS_USED_TOTAL,
  EST_COST_USD
)
SELECT
  DATE(START_TIME) AS USAGE_DATE,
  WAREHOUSE_NAME,
  SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE,
  SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
  SUM(CREDITS_USED) AS CREDITS_USED_TOTAL,
  SUM(CREDITS_USED) * $CREDIT_PRICE AS EST_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME::DATE >= DATEADD('day', -$DAYS_BACK, CURRENT_DATE())
GROUP BY 1,2;

-- C) DAILY_QUERY_METRICS refresh
DELETE FROM FINOPS.SNOWFLAKE_USAGE.DAILY_QUERY_METRICS
WHERE USAGE_DATE >= DATEADD('day', -$DAYS_BACK, CURRENT_DATE());

INSERT INTO FINOPS.SNOWFLAKE_USAGE.DAILY_QUERY_METRICS
(
  USAGE_DATE, WAREHOUSE_NAME, DATABASE_NAME, SCHEMA_NAME, USER_NAME, ROLE_NAME,
  QUERY_TYPE, EXECUTION_STATUS,
  QUERY_COUNT, TOTAL_ELAPSED_MS, AVG_ELAPSED_MS, TOTAL_BYTES_SCANNED
)
SELECT
  START_TIME::DATE AS USAGE_DATE,
  WAREHOUSE_NAME,
  DATABASE_NAME,
  SCHEMA_NAME,
  USER_NAME,
  ROLE_NAME,
  QUERY_TYPE,
  EXECUTION_STATUS,
  COUNT(*) AS QUERY_COUNT,
  SUM(TOTAL_ELAPSED_TIME) AS TOTAL_ELAPSED_MS,
  AVG(TOTAL_ELAPSED_TIME) AS AVG_ELAPSED_MS,
  SUM(BYTES_SCANNED) AS TOTAL_BYTES_SCANNED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME::DATE >= DATEADD('day', -$DAYS_BACK, CURRENT_DATE())
  AND WAREHOUSE_NAME IS NOT NULL
GROUP BY 1,2,3,4,5,6,7,8;

-- D) Heatmap table (dow/hour)
-- Note: WAREHOUSE_METERING_HISTORY is not hourly; use QUERY_HISTORY start_time distribution
-- This is "activity heat", not exact credit per hour.
DELETE FROM FINOPS.SNOWFLAKE_USAGE.HOURLY_WAREHOUSE_CREDITS
WHERE USAGE_DATE_TO = CURRENT_DATE();

INSERT INTO FINOPS.SNOWFLAKE_USAGE.HOURLY_WAREHOUSE_CREDITS
(DOW, HOUR_OF_DAY, WAREHOUSE_NAME, CREDITS_USED, EST_COST_USD, USAGE_DATE_FROM, USAGE_DATE_TO)
SELECT
  DAYOFWEEKISO(START_TIME) AS DOW,
  EXTRACT(HOUR FROM START_TIME) AS HOUR_OF_DAY,
  WAREHOUSE_NAME,
  -- Approx credits: allocate warehouse daily credits proportionally by query count in that hour
  0.0::NUMBER(38,9) AS CREDITS_USED, -- optional: keep 0 and heatmap by query_count instead
  0.0::NUMBER(38,9) AS EST_COST_USD,
  DATEADD('day', -$DAYS_BACK, CURRENT_DATE()) AS USAGE_DATE_FROM,
  CURRENT_DATE() AS USAGE_DATE_TO
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME::DATE >= DATEADD('day', -$DAYS_BACK, CURRENT_DATE())
  AND WAREHOUSE_NAME IS NOT NULL
GROUP BY 1,2,3;

-- E) Storage (optional) - database_storage_usage_history is a good source
DELETE FROM FINOPS.SNOWFLAKE_USAGE.DAILY_STORAGE
WHERE USAGE_DATE >= DATEADD('day', -$DAYS_BACK, CURRENT_DATE());

INSERT INTO FINOPS.SNOWFLAKE_USAGE.DAILY_STORAGE
(USAGE_DATE, DATABASE_NAME, AVERAGE_DATABASE_BYTES, AVERAGE_FAILSAFE_BYTES, EST_STORAGE_GB)
SELECT
  USAGE_DATE::DATE,
  DATABASE_NAME,
  AVG(AVERAGE_DATABASE_BYTES) AS AVERAGE_DATABASE_BYTES,
  AVG(AVERAGE_FAILSAFE_BYTES) AS AVERAGE_FAILSAFE_BYTES,
  ROUND(AVG(AVERAGE_DATABASE_BYTES) / 1024 / 1024 / 1024, 2) AS EST_STORAGE_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE USAGE_DATE::DATE >= DATEADD('day', -$DAYS_BACK, CURRENT_DATE())
GROUP BY 1,2;


SHOW MODELS IN ACCOUNT;

USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS CORTEX_USER;

GRANT USAGE ON FUNCTION SNOWFLAKE.CORTEX.COMPLETE(VARCHAR, OBJECT)
TO ROLE CORTEX_USER;

GRANT ROLE CORTEX_USER TO ROLE SYSADMIN;

SELECT SNOWFLAKE.CORTEX.COMPLETE(
  'snowflake-arctic',
  OBJECT_CONSTRUCT(
    'messages', ARRAY_CONSTRUCT(
      OBJECT_CONSTRUCT(
        'role', 'user',
        'content', 'Say hello from Snowflake Cortex'
      )
    )
  )
) AS RESPONSE;


SELECT CURRENT_ROLE();
